### ISSUE TITLE
Local variables must be camelCase, Not PascalCase

### ISSUE THREAD

**Issue by ssaravanan-pk** [kavyasreepurini/KAVYA-PHONEBOOK#11]
https://github.com/kavyasreepurini/KAVYA-PHONEBOOK/blob/d2a4bb4f9f5a1ecb88fca9d1075a90803c47f047/Program.cs#L27

Here is recommended casing for all cases. Read it. Follow it.
https://github.com/ktaranov/naming-convention/blob/master/C%23%20Coding%20Standards%20and%20Naming%20Conventions.md

**Comment by kavyasreepurini** [comment]
issue corrected
