### ISSUE TITLE
Name space has to be ProperCase or even dot separated. See how Microsoft named their namespaces.

### ISSUE THREAD

**Issue by ssaravanan-pk** [kavyasreepurini/KAVYA-PHONEBOOK#2]
https://github.com/kavyasreepurini/KAVYA-PHONEBOOK/blob/d2a4bb4f9f5a1ecb88fca9d1075a90803c47f047/consoleHandler.cs#L2

**Comment by kavyasreepurini** [comment]
issue corrected
